name: Source Workflow

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      pat_token: ${{ secrets.PAT_TOKEN_GITHUB }}
      parameter1: 'Feat'
      parameter2: 'V3.0.0'
    steps:
      - uses: actions/checkout@v3  

  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          echo "This is Source repo"
          echo""
          echo "Triggers workflow of Target repo"        
      - name: Trigger the target workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: AruNiv
          repo: Target_Workflow
          github_token: ${{ secrets.Token }}
          
          workflow_file_name: target_workflow.yml
          ref: main
          wait_interval: 10
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
