name: Source Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs: 
      calledworkflow_name:
        description: 'Target workflow Name for Triggering'
        required: true
        default: 'Target_Workflow'
      
      CalledWorkflow_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: 'AruNiv'
      
      CalledWorkflow_repo_github:
        description: 'GitHub Repository Name'
        required: true
        default: 'InvokeGitHubActionsCalled'

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    env: 
      pat_token: ${{ secrets.PAT_TOKEN_GITHUB }}
      parameter1: '42574587345'
      parameter2: 'TestStringWithoutSpace'

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          echo "This is Source repo"
          echo""
          echo "Triggers workflow of Target repo"        
      - name: Trigger the target workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: AruNiv
          repo: Target_Workflow
          github_token: ${{ secrets.Token }}
          workflow_file_name: target_workflow.yml
          ref: main
          wait_interval: 10
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
